### ISSUE TITLE
Increase clients_max

### ISSUE THREAD

**Issue by wilsonianb** [coilhq/tigerbeetle#44]
I'm attempting to run multiple application test suites concurrently against a single TigerBeetle instance (in Docker) and am running into the [`clients_max`](https://github.com/coilhq/tigerbeetle/blob/e2f47ebcca20d1a59fadca0a4ada56c92dcd231c/src/config.zig#L14) limit.
Can the default value be raised to 10+ and/or can it be made configurable via the cli?

**Comment by jorangreef** [comment]
Thanks @wilsonianb yes, `clients_max` was reduced to 3 for the bug bounty to conserve memory used by the VOPR. However, this leaked onto main accidentally.

I've set the max limit back up to 32. This would eventually be configurable via the CLI at `init` time for the cluster. Once configured for a particular cluster, it would need thereafter need to remain constant, otherwise it would make the client eviction logic in the state machine non-deterministic.
