### ISSUE TITLE
already_auto_committed unused

### ISSUE THREAD

**Issue by wilsonianb** [coilhq/tigerbeetle#52]
[`CommitTransferError.already_auto_committed`](https://github.com/coilhq/tigerbeetle-node/blob/main/src/index.ts#L133) doesn't appear to used.

Is it correct to assume that `transfer_not_two_phase_commit` means it was already auto-committed?

**Comment by jorangreef** [comment]
> CommitTransferError.already_auto_committed doesn't appear to used.

Thanks @wilsonianb good catch! Yes, `already_auto_committed` is a relic from before our types refactor, and should be removed from `tigerbeetle.zig` and from the TypeScript file for our Node.js client, since it's no longer returned by the state machine.

> Is it correct to assume that transfer_not_two_phase_commit means it was already auto-committed?

Yes, it means that one is trying to `commit` a transfer which is not a two-phase transfer, but a one-phase transfer (what was previously called an "auto-committing" transfer before the types refactor).

**Comment by koekiebox** [comment]
Enum's removed from TB and TB-Node client.
@wilsonianb please re-open case if you do not agree.

**Comment by jorangreef** [comment]
Thanks @wilsonianb and @koekiebox
