### ISSUE TITLE
Inline fn error with latest zig

### ISSUE THREAD

**Issue by wilsonianb** [coilhq/tigerbeetle#7]
Following the current [quickstart](https://github.com/coilhq/tigerbeetle#quickstart) produces the following error:
```
./src/tigerbeetle.zig:74:9: error: expected function or variable declaration after pub
    pub inline fn exceeds(balance: u64, amount: u64, limit: u64) bool {
        ^
```
I think this is due to https://github.com/ziglang/zig/pull/7749
tigerbeetle starts successfully with zig 0.7.1

**Comment by jorangreef** [comment]
Thanks @wilsonianb!

Running `scripts/install_zig.sh` will now install 0.7.1 as the latest stable release by default, so that everything works on TigerBeetle master branch (quick start, demos etc).

You can also now pass `master` as an arg to the script if you do want the latest nightly from master.
